"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['alien.png','bg2.png','box.png','giggle.mp3','high_score.txt','jump.wav','level.wav','music.mp3','p1_front.png',
              'p1_jump.png','p1_walk01.png','p1_walk02.png','p1_walk03.png','p1_walk04.png','p1_walk05.png'
              ,'p1_walk06.png','p1_walk07.png','p1_walk08.png','p1_walk09.png','p1_walk10.png','p1_walk11.png','tribbles.icns']
OPTIONS = {'iconfile':'tribbles.icns',}

setup(
    name="Tribbles",
    version="1.0",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
